env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - standard
  - plugin:jest/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - jest
globals:
  - JSX: true
  - React: true
rules:
  import/no-default-export: "off"
  no-use-before-define: "off"
  "@typescript-eslint/no-use-before-define":
    - "error"
