env:
  browser: true
  es2022: true
extends:
  - airbnb
  - airbnb-typescript
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
parserOptions:
  project: './tsconfig.eslint.json'
settings:
  react:
    version: "18.1.0"
  import/resolver:
    typescript: []
plugins:
  - '@typescript-eslint'
  - react
  - react-hooks
  - react-refresh
  - vitest
globals:
  React: true
  JSX: true
rules:
  "@typescript-eslint/no-misused-promises": "off"
  "@typescript-eslint/no-use-before-define":
    - "error"
  "@typescript-eslint/consistent-type-imports":
    - "error"
  import/no-default-export: "off"
  import/prefer-default-export: "off"
  jsx-a11y/label-has-associated-control: "off"
  no-nested-ternary: "off"
  no-use-before-define: "off"
  no-param-reassign: "off"
  react/jsx-props-no-spreading: "off"
  react/jsx-no-useless-fragment: "off"
  react/no-unused-prop-types: "off"
  react/require-default-props: "off"
  react-refresh/only-export-components: "warn"
