env:
  browser: true
  es2022: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:@typescript-eslint/stylistic-type-checked
parserOptions:
  project: './tsconfig.eslint.json'
settings:
  react:
    version: "18.2.0"
  import/resolver:
    typescript: []
plugins:
  - '@typescript-eslint'
  - react
  - react-hooks
  - react-refresh
  - strict-dependencies
  - vitest
globals:
  React: true
  JSX: true
rules:
  # 許容
  "@typescript-eslint/no-misused-promises": "off"
  "@typescript-eslint/consistent-type-definitions": "off"
  import/no-default-export: "off"
  import/prefer-default-export: "off"
  jsx-a11y/label-has-associated-control: "off"
  no-nested-ternary: "off"
  react/jsx-props-no-spreading: "off"
  react/jsx-no-useless-fragment: "off"
  react/no-unused-prop-types: "off"
  react/require-default-props: "off"
  # swc向け https://github.com/ArnaudBarre/eslint-plugin-react-refresh
  react-refresh/only-export-components: error
  # 強化
  "@typescript-eslint/no-use-before-define": error
  "@typescript-eslint/consistent-type-imports": error
  # 未使用変数はアンダーバー開始のものを許容
  '@typescript-eslint/no-unused-vars':
    - warn
    - argsIgnorePattern: ^_
      varsIgnorePattern: ^_
      caughtErrorsIgnorePattern: ^_
      destructuredArrayIgnorePattern: ^_
  # 依存関係の階層設定
  strict-dependencies/strict-dependencies:
    - "error"
    - - module: ./src/features/*/thunk
        allowReferenceFrom:
          - ./src/features/*
        allowSameModule: true
      - module: ./src/features/*
        allowReferenceFrom:
          - ./src/pages/*
        allowSameModule: true
      - module: ./src/pages/components/*
        allowReferenceFrom:
          - ./src/*.tsx
          - ./src/pages/*
        allowSameModule: true
    - resolveRelativeImport: true

