[api]

[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"

[providers.file]
  directory = "/etc/traefik/configuration"
  watch = true

[providers.docker]
  exposedByDefault = false
  watch = true